// <auto-generated />
namespace KariyerPortali.Admin.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addmigrationIlkMigration : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addmigrationIlkMigration));
        
        string IMigrationMetadata.Id
        {
            get { return "201611041303365_add-migration IlkMigration"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
